### ISSUE TITLE
Error building musiccabinet

### ISSUE THREAD

**Issue by aaronromeo** [hakko/musiccabinet#15]
Hi there,

I have a problem building this project based on the instructions from subsonic project.

Below is my stack trace.  Please let me know if I can provide you with any other information.

Thanks,
Aaron.

aaron@theone:~/workspace/musiccabinet/musiccabinet-server$ mvn -e -X exec:java -Dexec.mainClass=com.github.hakko.musiccabinet.service.DatabaseAdministrationService
Apache Maven 3.0.4
Maven home: /usr/share/maven
Java version: 1.7.0_06, vendor: Oracle Corporation
Java home: /usr/lib/jvm/java-7-oracle/jre
Default locale: en_CA, platform encoding: UTF-8
OS name: "linux", version: "3.2.0-29-generic-pae", arch: "i386", family: "unix"
[INFO] Error stacktraces are turned on.
[DEBUG] Reading global settings from /usr/share/maven/conf/settings.xml
[DEBUG] Reading user settings from /home/aaron/.m2/settings.xml
[DEBUG] Using local repository at /home/aaron/.m2/repository
[DEBUG] Using manager EnhancedLocalRepositoryManager with priority 10 for /home/aaron/.m2/repository
[INFO] Scanning for projects...
[DEBUG] Extension realms for project com.github.hakko.musiccabinet:musiccabinet-server:jar:0.7.7: (none)
[DEBUG] Looking up lifecyle mappings for packaging jar from ClassRealm[plexus.core, parent: null]
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for com.github.hakko.musiccabinet:musiccabinet-server:jar:0.7.7
[WARNING] 'version' contains an expression but should be a constant. @ com.github.hakko.musiccabinet:musiccabinet-server:${version.musiccabinet}, /home/aaron/workspace/musiccabinet/musiccabinet-server/pom.xml, line 25, column 11
[WARNING] 
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING] 
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING] 
[DEBUG] Resolving plugin prefix exec from [org.apache.maven.plugins, org.codehaus.mojo]
[DEBUG] Could not find metadata org.apache.maven.plugins/maven-metadata.xml in local (/home/aaron/.m2/repository)
[DEBUG] Skipped remote update check for org.apache.maven.plugins/maven-metadata.xml, locally cached metadata up-to-date.
[DEBUG] Could not find metadata org.codehaus.mojo/maven-metadata.xml in local (/home/aaron/.m2/repository)
[DEBUG] Skipped remote update check for org.codehaus.mojo/maven-metadata.xml, locally cached metadata up-to-date.
[DEBUG] Resolved plugin prefix exec to org.codehaus.mojo:exec-maven-plugin from repository central
[DEBUG] Resolving plugin version for org.codehaus.mojo:exec-maven-plugin
[DEBUG] Could not find metadata org.codehaus.mojo:exec-maven-plugin/maven-metadata.xml in local (/home/aaron/.m2/repository)
[DEBUG] Skipped remote update check for org.codehaus.mojo:exec-maven-plugin/maven-metadata.xml, locally cached metadata up-to-date.
[DEBUG] Resolved plugin version for org.codehaus.mojo:exec-maven-plugin to 1.2.1 from repository central (http://repo.maven.apache.org/maven2, releases)
[DEBUG] === REACTOR BUILD PLAN ================================================
[DEBUG] Project: com.github.hakko.musiccabinet:musiccabinet-server:jar:0.7.7
[DEBUG] Tasks:   [exec:java]
[DEBUG] Style:   Regular
[DEBUG] =======================================================================
[INFO]  
[INFO] ------------------------------------------------------------------------
[INFO] Building musiccabinet-server 0.7.7
[INFO] ------------------------------------------------------------------------
[DEBUG] Resolving plugin prefix exec from [org.apache.maven.plugins, org.codehaus.mojo]
[DEBUG] Could not find metadata org.apache.maven.plugins/maven-metadata.xml in local (/home/aaron/.m2/repository)
[DEBUG] Skipped remote update check for org.apache.maven.plugins/maven-metadata.xml, locally cached metadata up-to-date.
[DEBUG] Could not find metadata org.codehaus.mojo/maven-metadata.xml in local (/home/aaron/.m2/repository)
[DEBUG] Skipped remote update check for org.codehaus.mojo/maven-metadata.xml, locally cached metadata up-to-date.
[DEBUG] Resolved plugin prefix exec to org.codehaus.mojo:exec-maven-plugin from repository central
[DEBUG] Resolving plugin version for org.codehaus.mojo:exec-maven-plugin
[DEBUG] Could not find metadata org.codehaus.mojo:exec-maven-plugin/maven-metadata.xml in local (/home/aaron/.m2/repository)
[DEBUG] Skipped remote update check for org.codehaus.mojo:exec-maven-plugin/maven-metadata.xml, locally cached metadata up-to-date.
[DEBUG] Resolved plugin version for org.codehaus.mojo:exec-maven-plugin to 1.2.1 from repository central (http://repo.maven.apache.org/maven2, releases)
[DEBUG] Lifecycle default -> [validate, initialize, generate-sources, process-sources, generate-resources, process-resources, compile, process-classes, generate-test-sources, process-test-sources, generate-test-resources, process-test-resources, test-compile, process-test-classes, test, prepare-package, package, pre-integration-test, integration-test, post-integration-test, verify, install, deploy]
[DEBUG] Lifecycle clean -> [pre-clean, clean, post-clean]
[DEBUG] Lifecycle site -> [pre-site, site, post-site, site-deploy]
[DEBUG] Lifecycle default -> [validate, initialize, generate-sources, process-sources, generate-resources, process-resources, compile, process-classes, generate-test-sources, process-test-sources, generate-test-resources, process-test-resources, test-compile, process-test-classes, test, prepare-package, package, pre-integration-test, integration-test, post-integration-test, verify, install, deploy]
[DEBUG] Lifecycle clean -> [pre-clean, clean, post-clean]
[DEBUG] Lifecycle site -> [pre-site, site, post-site, site-deploy]
[DEBUG] === PROJECT BUILD PLAN ================================================
[DEBUG] Project:       com.github.hakko.musiccabinet:musiccabinet-server:0.7.7
[DEBUG] Dependencies (collect): []
[DEBUG] Dependencies (resolve): [test]
[DEBUG] Repositories (dependencies): [com.springsource.repository.bundles.release (http://repository.springsource.com/maven/bundles/release, releases+snapshots), com.springsource.repository.bundles.external (http://repository.springsource.com/maven/bundles/external, releases+snapshots), repository.springframework.maven.release (http://maven.springframework.org/release, releases+snapshots), central (http://repo.maven.apache.org/maven2, releases)]
[DEBUG] Repositories (plugins)     : [central (http://repo.maven.apache.org/maven2, releases)]
[DEBUG] --- init fork of com.github.hakko.musiccabinet:musiccabinet-server:0.7.7 for org.codehaus.mojo:exec-maven-plugin:1.2.1:java (default-cli) ---
[DEBUG] Dependencies (collect): []
[DEBUG] Dependencies (resolve): []
[DEBUG] --- exit fork of com.github.hakko.musiccabinet:musiccabinet-server:0.7.7 for org.codehaus.mojo:exec-maven-plugin:1.2.1:java (default-cli) ---
[DEBUG] -----------------------------------------------------------------------
[DEBUG] Goal:          org.codehaus.mojo:exec-maven-plugin:1.2.1:java (default-cli)
[DEBUG] Style:         Regular
[DEBUG] Configuration: <?xml version="1.0" encoding="UTF-8"?>
<configuration>
  <arguments>${exec.arguments}</arguments>
  <classpathScope default-value="runtime">${exec.classpathScope}</classpathScope>
  <cleanupDaemonThreads>${exec.cleanupDaemonThreads} default-value=</cleanupDaemonThreads>
  <commandlineArgs>${exec.args}</commandlineArgs>
  <daemonThreadJoinTimeout default-value="15000">${exec.daemonThreadJoinTimeout}</daemonThreadJoinTimeout>
  <includePluginDependencies default-value="false">${exec.includePluginDependencies}</includePluginDependencies>
  <includeProjectDependencies default-value="true">${exec.includeProjectDependencies}</includeProjectDependencies>
  <keepAlive default-value="false">${exec.keepAlive}</keepAlive>
  <killAfter default-value="-1">${exec.killAfter}</killAfter>
  <localRepository default-value="${localRepository}"/>
  <mainClass>${exec.mainClass}</mainClass>
  <pluginDependencies default-value="${plugin.artifacts}"/>
  <project default-value="${project}"/>
  <remoteRepositories default-value="${project.remoteArtifactRepositories}"/>
  <skip default-value="false">${skip}</skip>
  <sourceRoot>${sourceRoot}</sourceRoot>
  <stopUnresponsiveDaemonThreads>${exec.stopUnresponsiveDaemonThreads} default-value=</stopUnresponsiveDaemonThreads>
  <testSourceRoot>${testSourceRoot}</testSourceRoot>
</configuration>
[DEBUG] =======================================================================
[INFO] 
[INFO] >>> exec-maven-plugin:1.2.1:java (default-cli) @ musiccabinet-server >>>
[INFO] 
[INFO] <<< exec-maven-plugin:1.2.1:java (default-cli) @ musiccabinet-server <<<
[DEBUG] com.github.hakko.musiccabinet:musiccabinet-server:jar:0.7.7
[DEBUG]    commons-lang:commons-lang:jar:2.5:compile
[DEBUG]    commons-io:commons-io:jar:2.4:compile
[DEBUG]    joda-time:joda-time:jar:2.0:compile
[DEBUG]    com.mchange:c3p0:jar:0.9.2-pre4:compile
[DEBUG]       com.mchange:mchange-commons-java:jar:0.2.2:compile
[DEBUG]    postgresql:postgresql:jar:9.0-801.jdbc4:compile
[DEBUG]    org.apache.httpcomponents:httpclient:jar:4.1.2:compile
[DEBUG]       org.apache.httpcomponents:httpcore:jar:4.1.2:compile
[DEBUG]       commons-logging:commons-logging:jar:1.1.1:compile
[DEBUG]       commons-codec:commons-codec:jar:1.4:compile
[DEBUG]    org.codehaus.woodstox:woodstox-core-asl:jar:4.1.2:compile
[DEBUG]       javax.xml.stream:stax-api:jar:1.0-2:compile
[DEBUG]       org.codehaus.woodstox:stax2-api:jar:3.1.1:compile
[DEBUG]    org:jaudiotagger:jar:2.0.2:compile
[DEBUG]    junit:junit:jar:4.8.2:test
[DEBUG]    org.mockito:mockito-core:jar:1.9.0:test
[DEBUG]       org.hamcrest:hamcrest-core:jar:1.1:test
[DEBUG]       org.objenesis:objenesis:jar:1.0:test
[DEBUG]    org.springframework:org.springframework.core:jar:3.1.0.RELEASE:compile
[DEBUG]    org.springframework:spring-beans:jar:3.1.0.RELEASE:compile
[DEBUG]       org.springframework:spring-core:jar:3.1.0.RELEASE:compile
[DEBUG]    org.springframework:spring-context:jar:3.1.0.RELEASE:compile
[DEBUG]       org.springframework:spring-aop:jar:3.1.0.RELEASE:compile
[DEBUG]       org.springframework:spring-expression:jar:3.1.0.RELEASE:compile
[DEBUG]       org.springframework:spring-asm:jar:3.1.0.RELEASE:compile
[DEBUG]    org.springframework:spring-tx:jar:3.1.0.RELEASE:compile
[DEBUG]       aopalliance:aopalliance:jar:1.0:compile
[DEBUG]    org.springframework:spring-jdbc:jar:3.1.0.RELEASE:compile
[DEBUG]    org.springframework:spring-test:jar:3.1.0.RELEASE:test
[DEBUG]    org.springframework.integration:spring-integration-core:jar:2.1.1.RELEASE:compile
[INFO] 
[INFO] --- exec-maven-plugin:1.2.1:java (default-cli) @ musiccabinet-server ---
[DEBUG] Created new class realm maven.api
[DEBUG] Importing foreign packages into class realm maven.api
[DEBUG]   Imported: org.apache.maven.wagon.events < plexus.core
[DEBUG]   Imported: org.sonatype.aether.transfer < plexus.core
[DEBUG]   Imported: org.apache.maven.exception < plexus.core
[DEBUG]   Imported: org.sonatype.aether.metadata < plexus.core
[DEBUG]   Imported: org.codehaus.plexus.util.xml.Xpp3Dom < plexus.core
[DEBUG]   Imported: org.sonatype.aether.collection < plexus.core
[DEBUG]   Imported: org.sonatype.aether.version < plexus.core
[DEBUG]   Imported: org.apache.maven.monitor < plexus.core
[DEBUG]   Imported: org.apache.maven.wagon.repository < plexus.core
[DEBUG]   Imported: org.apache.maven.repository < plexus.core
[DEBUG]   Imported: org.apache.maven.wagon.resource < plexus.core
[DEBUG]   Imported: org.codehaus.plexus.logging < plexus.core
[DEBUG]   Imported: org.apache.maven.profiles < plexus.core
[DEBUG]   Imported: org.sonatype.aether.repository < plexus.core
[DEBUG]   Imported: org.apache.maven.classrealm < plexus.core
[DEBUG]   Imported: org.apache.maven.execution < plexus.core
[DEBUG]   Imported: org.sonatype.aether.artifact < plexus.core
[DEBUG]   Imported: org.sonatype.aether.spi < plexus.core
[DEBUG]   Imported: org.apache.maven.reporting < plexus.core
[DEBUG]   Imported: org.apache.maven.usability < plexus.core
[DEBUG]   Imported: org.codehaus.plexus.container < plexus.core
[DEBUG]   Imported: org.codehaus.plexus.component < plexus.core
[DEBUG]   Imported: org.codehaus.plexus.util.xml.pull.XmlSerializer < plexus.core
[DEBUG]   Imported: org.apache.maven.wagon.authentication < plexus.core
[DEBUG]   Imported: org.apache.maven.lifecycle < plexus.core
[DEBUG]   Imported: org.codehaus.plexus.classworlds < plexus.core
[DEBUG]   Imported: org.sonatype.aether.graph < plexus.core
[DEBUG]   Imported: org.sonatype.aether.\* < plexus.core
[DEBUG]   Imported: org.apache.maven.settings < plexus.core
[DEBUG]   Imported: org.codehaus.classworlds < plexus.core
[DEBUG]   Imported: org.sonatype.aether.impl < plexus.core
[DEBUG]   Imported: org.apache.maven.wagon.\* < plexus.core
[DEBUG]   Imported: org.apache.maven.toolchain < plexus.core
[DEBUG]   Imported: org.sonatype.aether.deployment < plexus.core
[DEBUG]   Imported: org.apache.maven.wagon.observers < plexus.core
[DEBUG]   Imported: org.codehaus.plexus.util.xml.pull.XmlPullParserException < plexus.core
[DEBUG]   Imported: org.codehaus.plexus.util.xml.pull.XmlPullParser < plexus.core
[DEBUG]   Imported: org.apache.maven.configuration < plexus.core
[DEBUG]   Imported: org.apache.maven.cli < plexus.core
[DEBUG]   Imported: org.sonatype.aether.installation < plexus.core
[DEBUG]   Imported: org.codehaus.plexus.context < plexus.core
[DEBUG]   Imported: org.apache.maven.wagon.authorization < plexus.core
[DEBUG]   Imported: org.apache.maven.project < plexus.core
[DEBUG]   Imported: org.apache.maven.rtinfo < plexus.core
[DEBUG]   Imported: org.codehaus.plexus.lifecycle < plexus.core
[DEBUG]   Imported: org.codehaus.plexus.configuration < plexus.core
[DEBUG]   Imported: org.apache.maven.artifact < plexus.core
[DEBUG]   Imported: org.apache.maven.model < plexus.core
[DEBUG]   Imported: org.apache.maven.\* < plexus.core
[DEBUG]   Imported: org.apache.maven.wagon.proxy < plexus.core
[DEBUG]   Imported: org.sonatype.aether.resolution < plexus.core
[DEBUG]   Imported: org.apache.maven.plugin < plexus.core
[DEBUG]   Imported: org.codehaus.plexus.\* < plexus.core
[DEBUG]   Imported: org.codehaus.plexus.personality < plexus.core
[DEBUG] Populating class realm maven.api
[DEBUG] org.codehaus.mojo:exec-maven-plugin:jar:1.2.1:
[DEBUG]    org.apache.maven:maven-toolchain:jar:1.0:compile
[DEBUG]    org.apache.maven:maven-project:jar:2.0.6:compile
[DEBUG]       org.apache.maven:maven-settings:jar:2.0.6:compile
[DEBUG]       org.apache.maven:maven-profile:jar:2.0.6:compile
[DEBUG]       org.apache.maven:maven-plugin-registry:jar:2.0.6:compile
[DEBUG]    org.apache.maven:maven-model:jar:2.0.6:compile
[DEBUG]    org.apache.maven:maven-artifact:jar:2.0.6:compile
[DEBUG]    org.apache.maven:maven-artifact-manager:jar:2.0.6:compile
[DEBUG]       org.apache.maven:maven-repository-metadata:jar:2.0.6:compile
[DEBUG]    org.apache.maven:maven-core:jar:2.0.6:compile
[DEBUG]       org.apache.maven:maven-plugin-parameter-documenter:jar:2.0.6:compile
[DEBUG]       org.apache.maven.reporting:maven-reporting-api:jar:2.0.6:compile
[DEBUG]          org.apache.maven.doxia:doxia-sink-api:jar:1.0-alpha-7:compile
[DEBUG]       org.apache.maven:maven-error-diagnostics:jar:2.0.6:compile
[DEBUG]       commons-cli:commons-cli:jar:1.0:compile
[DEBUG]       org.apache.maven:maven-plugin-descriptor:jar:2.0.6:compile
[DEBUG]       org.codehaus.plexus:plexus-interactivity-api:jar:1.0-alpha-4:compile
[DEBUG]       org.apache.maven:maven-monitor:jar:2.0.6:compile
[DEBUG]       classworlds:classworlds:jar:1.1:compile
[DEBUG]    org.apache.maven:maven-plugin-api:jar:2.0.6:compile
[DEBUG]    org.codehaus.plexus:plexus-utils:jar:2.0.5:compile
[DEBUG]    org.codehaus.plexus:plexus-container-default:jar:1.0-alpha-9:compile
[DEBUG]       junit:junit:jar:3.8.2:test (scope managed from compile) (version managed from 3.8.1)
[DEBUG]    org.apache.commons:commons-exec:jar:1.1:compile
[DEBUG] Created new class realm plugin>org.codehaus.mojo:exec-maven-plugin:1.2.1
[DEBUG] Importing foreign packages into class realm plugin>org.codehaus.mojo:exec-maven-plugin:1.2.1
[DEBUG]   Imported:  < maven.api
[DEBUG] Populating class realm plugin>org.codehaus.mojo:exec-maven-plugin:1.2.1
[DEBUG]   Included: org.codehaus.mojo:exec-maven-plugin:jar:1.2.1
[DEBUG]   Included: org.apache.maven.reporting:maven-reporting-api:jar:2.0.6
[DEBUG]   Included: org.apache.maven.doxia:doxia-sink-api:jar:1.0-alpha-7
[DEBUG]   Included: commons-cli:commons-cli:jar:1.0
[DEBUG]   Included: org.codehaus.plexus:plexus-interactivity-api:jar:1.0-alpha-4
[DEBUG]   Included: org.codehaus.plexus:plexus-utils:jar:2.0.5
[DEBUG]   Included: org.apache.commons:commons-exec:jar:1.1
[DEBUG]   Excluded: org.apache.maven:maven-toolchain:jar:1.0
[DEBUG]   Excluded: org.apache.maven:maven-project:jar:2.0.6
[DEBUG]   Excluded: org.apache.maven:maven-settings:jar:2.0.6
[DEBUG]   Excluded: org.apache.maven:maven-profile:jar:2.0.6
[DEBUG]   Excluded: org.apache.maven:maven-plugin-registry:jar:2.0.6
[DEBUG]   Excluded: org.apache.maven:maven-model:jar:2.0.6
[DEBUG]   Excluded: org.apache.maven:maven-artifact:jar:2.0.6
[DEBUG]   Excluded: org.apache.maven:maven-artifact-manager:jar:2.0.6
[DEBUG]   Excluded: org.apache.maven:maven-repository-metadata:jar:2.0.6
[DEBUG]   Excluded: org.apache.maven:maven-core:jar:2.0.6
[DEBUG]   Excluded: org.apache.maven:maven-plugin-parameter-documenter:jar:2.0.6
[DEBUG]   Excluded: org.apache.maven:maven-error-diagnostics:jar:2.0.6
[DEBUG]   Excluded: org.apache.maven:maven-plugin-descriptor:jar:2.0.6
[DEBUG]   Excluded: org.apache.maven:maven-monitor:jar:2.0.6
[DEBUG]   Excluded: classworlds:classworlds:jar:1.1
[DEBUG]   Excluded: org.apache.maven:maven-plugin-api:jar:2.0.6
[DEBUG]   Excluded: org.codehaus.plexus:plexus-container-default:jar:1.0-alpha-9
[DEBUG]   Excluded: junit:junit:jar:3.8.2
[DEBUG] Configuring mojo org.codehaus.mojo:exec-maven-plugin:1.2.1:java from plugin realm ClassRealm[plugin>org.codehaus.mojo:exec-maven-plugin:1.2.1, parent: sun.misc.Launcher$AppClassLoader@156e0b4]
[DEBUG] Configuring mojo 'org.codehaus.mojo:exec-maven-plugin:1.2.1:java' with basic configurator -->
[DEBUG](f) arguments = []
[DEBUG](f) classpathScope = runtime
[DEBUG](f) cleanupDaemonThreads = false
[DEBUG](f) daemonThreadJoinTimeout = 15000
[DEBUG](f) includePluginDependencies = false
[DEBUG](f) includeProjectDependencies = true
[DEBUG](f) keepAlive = false
[DEBUG](f) killAfter = -1
[DEBUG](f) localRepository =        id: local
      url: file:///home/aaron/.m2/repository/
   layout: none

[DEBUG](f) mainClass = com.github.hakko.musiccabinet.service.DatabaseAdministrationService
[DEBUG](f) pluginDependencies = [org.codehaus.mojo:exec-maven-plugin:maven-plugin:1.2.1:, org.apache.maven.reporting:maven-reporting-api:jar:2.0.6:compile, org.apache.maven.doxia:doxia-sink-api:jar:1.0-alpha-7:compile, commons-cli:commons-cli:jar:1.0:compile, org.codehaus.plexus:plexus-interactivity-api:jar:1.0-alpha-4:compile, org.codehaus.plexus:plexus-utils:jar:2.0.5:compile, org.apache.commons:commons-exec:jar:1.1:compile]
[DEBUG](f) project = MavenProject: com.github.hakko.musiccabinet:musiccabinet-server:0.7.7 @ /home/aaron/workspace/musiccabinet/musiccabinet-server/pom.xml
[DEBUG](f) remoteRepositories = [       id: com.springsource.repository.bundles.release
      url: http://repository.springsource.com/maven/bundles/release
   layout: default
snapshots: [enabled => true, update => daily]
 releases: [enabled => true, update => daily]
,        id: com.springsource.repository.bundles.external
      url: http://repository.springsource.com/maven/bundles/external
   layout: default
snapshots: [enabled => true, update => daily]
 releases: [enabled => true, update => daily]
,        id: repository.springframework.maven.release
      url: http://maven.springframework.org/release
   layout: default
snapshots: [enabled => true, update => daily]
 releases: [enabled => true, update => daily]
,        id: central
      url: http://repo.maven.apache.org/maven2
   layout: default
snapshots: [enabled => false, update => daily]
 releases: [enabled => true, update => daily]
]
[DEBUG](f) skip = false
[DEBUG](f) stopUnresponsiveDaemonThreads = false
[DEBUG] -- end configuration --
[DEBUG] Invoking : com.github.hakko.musiccabinet.service.DatabaseAdministrationService.main()
[DEBUG] Plugin Dependencies will be excluded.
[DEBUG] Project Dependencies will be included.
[DEBUG] Collected project artifacts [commons-lang:commons-lang:jar:2.5:compile, commons-io:commons-io:jar:2.4:compile, joda-time:joda-time:jar:2.0:compile, com.mchange:c3p0:jar:0.9.2-pre4:compile, com.mchange:mchange-commons-java:jar:0.2.2:compile, postgresql:postgresql:jar:9.0-801.jdbc4:compile, org.apache.httpcomponents:httpclient:jar:4.1.2:compile, org.apache.httpcomponents:httpcore:jar:4.1.2:compile, commons-logging:commons-logging:jar:1.1.1:compile, commons-codec:commons-codec:jar:1.4:compile, org.codehaus.woodstox:woodstox-core-asl:jar:4.1.2:compile, javax.xml.stream:stax-api:jar:1.0-2:compile, org.codehaus.woodstox:stax2-api:jar:3.1.1:compile, org:jaudiotagger:jar:2.0.2:compile, org.springframework:org.springframework.core:jar:3.1.0.RELEASE:compile, org.springframework:spring-beans:jar:3.1.0.RELEASE:compile, org.springframework:spring-core:jar:3.1.0.RELEASE:compile, org.springframework:spring-context:jar:3.1.0.RELEASE:compile, org.springframework:spring-aop:jar:3.1.0.RELEASE:compile, org.springframework:spring-expression:jar:3.1.0.RELEASE:compile, org.springframework:spring-asm:jar:3.1.0.RELEASE:compile, org.springframework:spring-tx:jar:3.1.0.RELEASE:compile, aopalliance:aopalliance:jar:1.0:compile, org.springframework:spring-jdbc:jar:3.1.0.RELEASE:compile, org.springframework.integration:spring-integration-core:jar:2.1.1.RELEASE:compile]
[DEBUG] Collected project classpath [/home/aaron/workspace/musiccabinet/musiccabinet-server/target/classes]
[DEBUG] Adding to classpath : file:/home/aaron/workspace/musiccabinet/musiccabinet-server/target/classes
[DEBUG] Adding project dependency artifact: commons-lang to classpath
[DEBUG] Adding project dependency artifact: commons-io to classpath
[DEBUG] Adding project dependency artifact: joda-time to classpath
[DEBUG] Adding project dependency artifact: c3p0 to classpath
[DEBUG] Adding project dependency artifact: mchange-commons-java to classpath
[DEBUG] Adding project dependency artifact: postgresql to classpath
[DEBUG] Adding project dependency artifact: httpclient to classpath
[DEBUG] Adding project dependency artifact: httpcore to classpath
[DEBUG] Adding project dependency artifact: commons-logging to classpath
[DEBUG] Adding project dependency artifact: commons-codec to classpath
[DEBUG] Adding project dependency artifact: woodstox-core-asl to classpath
[DEBUG] Adding project dependency artifact: stax-api to classpath
[DEBUG] Adding project dependency artifact: stax2-api to classpath
[DEBUG] Adding project dependency artifact: jaudiotagger to classpath
[DEBUG] Adding project dependency artifact: org.springframework.core to classpath
[DEBUG] Adding project dependency artifact: spring-beans to classpath
[DEBUG] Adding project dependency artifact: spring-core to classpath
[DEBUG] Adding project dependency artifact: spring-context to classpath
[DEBUG] Adding project dependency artifact: spring-aop to classpath
[DEBUG] Adding project dependency artifact: spring-expression to classpath
[DEBUG] Adding project dependency artifact: spring-asm to classpath
[DEBUG] Adding project dependency artifact: spring-tx to classpath
[DEBUG] Adding project dependency artifact: aopalliance to classpath
[DEBUG] Adding project dependency artifact: spring-jdbc to classpath
[DEBUG] Adding project dependency artifact: spring-integration-core to classpath
[DEBUG] joining on thread Thread[com.github.hakko.musiccabinet.service.DatabaseAdministrationService.main(),5,com.github.hakko.musiccabinet.service.DatabaseAdministrationService]
[WARNING] 
java.lang.ClassNotFoundException: com.github.hakko.musiccabinet.service.DatabaseAdministrationService
    at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:423)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:356)
    at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:285)
    at java.lang.Thread.run(Thread.java:722)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1.737s
[INFO] Finished at: Fri Aug 24 11:34:57 EDT 2012
[INFO] Final Memory: 8M/109M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.2.1:java (default-cli) on project musiccabinet-server: An exception occured while executing the Java class. com.github.hakko.musiccabinet.service.DatabaseAdministrationService -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.2.1:java (default-cli) on project musiccabinet-server: An exception occured while executing the Java class. com.github.hakko.musiccabinet.service.DatabaseAdministrationService
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:217)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:84)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:59)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.singleThreadedBuild(LifecycleStarter.java:183)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:161)
    at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:320)
    at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:156)
    at org.apache.maven.cli.MavenCli.execute(MavenCli.java:537)
    at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:196)
    at org.apache.maven.cli.MavenCli.main(MavenCli.java:141)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:601)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:290)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:230)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:409)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:352)
Caused by: org.apache.maven.plugin.MojoExecutionException: An exception occured while executing the Java class. com.github.hakko.musiccabinet.service.DatabaseAdministrationService
    at org.codehaus.mojo.exec.ExecJavaMojo.execute(ExecJavaMojo.java:352)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:101)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:209)
    ... 19 more
Caused by: java.lang.ClassNotFoundException: com.github.hakko.musiccabinet.service.DatabaseAdministrationService
    at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:423)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:356)
    at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:285)
    at java.lang.Thread.run(Thread.java:722)
[ERROR] 
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

**Comment by hakko** [comment]
I'm sorry about that, it seems that I missed an import command (mvn compile). The instructions are updated and worked for me on a clean install. I'm closing this, but let me know if you run into any other trouble.
