### ISSUE TITLE
Usability with MySQL

### ISSUE THREAD

**Issue by lenucksi** [hakko/musiccabinet#20]
The Docs in the Subsonic-Forum say that Musiccabinet is only usable with PostgreSQL. I'ld love to be able to use it with the already present MySQL.

**Comment by hakko** [comment]
Supporting MySQL would require rewriting quite a lot of code (different syntax and different functionality sets, for example for free text search where I use pg_trgm). I personally don't think it's worth the effort as MySQL doesn't offer any extended features (that I'm aware of), rather the other way around. But feel free to fork if it's important for you! Or why not migrate your other app to PostgreSQL and consolidate to that.
