### ISSUE TITLE
Last.fm scrobbling from mobile clients

### ISSUE THREAD

**Issue by harahauk** [hakko/musiccabinet#22]
Hi!
Thanks for your great work.
Seems MusicCabinet does not scrobble when i play from mobile clients, this is a letdown in an otherwise very sweet setup I have now.

**Comment by hakko** [comment]
Isn't that something that you have to configure your mobile app to do? Subsonic/MusicCabinet exposes a method for apps to call when they have played a song, but the server is not aware if the app plays cached songs over and over etc. So the initiative must be taken by the app.

**Comment by harahauk** [comment]
Ah, I figured that since the server is aware of my playing from the mobile app (you can see it in the now playing window) there would be possible to add an option for scrobbling whether the mobile client supports it or not. That would be my feature request, with a option toggle in the settings of course. Thanks again.
Edit: It makes more sense to alter the client app.
